import type { CodexOfficialQuota, UsageReading } from "../api/client";
import { currentLanguage, tr } from "../i18n/current.ts";
import type { MessageKey } from "../i18n/messages.ts";

function exactValueFormatter(): Intl.NumberFormat {
  return new Intl.NumberFormat(currentLanguage(), { maximumFractionDigits: 2 });
}

function compactValueFormatter(): Intl.NumberFormat {
  return new Intl.NumberFormat(currentLanguage(), {
    notation: "compact",
    maximumFractionDigits: 1,
  });
}

/** Official windows are percentages; generic balances keep their source unit. */
export function officialQuotaReadings(quota: CodexOfficialQuota, compact = false): UsageReading[] {
  return quota.windows.map((window) => ({
    planName: officialQuotaWindowName(window.label, compact),
    remaining: 100 - window.usedPercent,
    used: window.usedPercent,
    total: 100,
    unit: "%",
    ...(window.resetsAt ? { resetsAt: window.resetsAt } : {}),
  }));
}

/** Formats a generic usage value with the unit carried by its source contract.
 * This keeps table values audit-friendly and leaves token-specific compaction
 * to the local-model token display contract. */
export function formatUsageValue(value: number | null | undefined, unit?: string | null): string {
  if (value === null || value === undefined || !Number.isFinite(value)) return "—";
  return appendUnit(exactValueFormatter().format(value), unit);
}

/** Compact axis-scale value. The chart caption owns the unit label, so this
 * intentionally returns only the scaled number rather than duplicating it on
 * every tick. */
export function formatCompactUsageValue(value: number): string {
  if (!Number.isFinite(value)) return "—";
  return compactValueFormatter().format(value);
}

function appendUnit(value: string, unit: string | null | undefined): string {
  const normalized = unit?.trim();
  return normalized === "%" ? `${value}%` : normalized ? `${value} ${normalized}` : value;
}

export function usageProgress(reading: UsageReading): number | null {
  if (reading.total === null || !Number.isFinite(reading.total) || reading.total <= 0) return null;
  const used = reading.used ?? (reading.remaining === null ? null : reading.total - reading.remaining);
  if (used === null || !Number.isFinite(used)) return null;
  return (used / reading.total) * 100;
}

/** Source-reported remaining wins; missing fields are never fabricated. */
export function usagePrimary(reading: UsageReading): { label: string; value: number } | null {
  if (reading.remaining !== null) {
    return {
      label: tr(reading.unit === "%" ? "format.usage.remaining" : "format.usage.balance"),
      value: reading.remaining,
    };
  }
  if (reading.used !== null) return { label: tr("format.usage.used"), value: reading.used };
  if (reading.total !== null) return { label: tr("format.usage.total"), value: reading.total };
  return null;
}

export function usageTone(reading: UsageReading): "danger" | undefined {
  return reading.isValid === false || (reading.remaining !== null && reading.remaining <= 0)
    ? "danger" : undefined;
}

/** Official window identifiers are generated by quota_window_label in Rust and
 * also identify persisted history and reset baselines. Translate only that
 * domain; provider-script plan names remain user content. */
export function officialQuotaWindowName(label: string, compact = false): string {
  const match = /^(\d+) (天|小时|分钟)$/.exec(label);
  if (!match) return label;
  const count = Number(match[1]);
  const unit = match[2] === "天" ? "days" : match[2] === "小时" ? "hours" : "minutes";
  if (compact) return `${count}${unit === "days" ? "d" : unit === "hours" ? "h" : "m"}`;
  const key: MessageKey = `format.window.${unit}${count === 1 ? "One" : "Many"}`;
  return tr(key, { count });
}

export function formatTrayReading(reading: UsageReading): string {
  if (reading.isValid === false) return tr("format.tray.invalidReading");
  const primary = usagePrimary(reading);
  if (!primary) return tr("format.tray.noReading");
  const value = `${primary.label} ${appendUnit(compactValueFormatter().format(primary.value), reading.unit)}`;
  return reading.remaining !== null && reading.remaining <= 0
    ? `${value} ${tr("format.tray.depleted")}` : value;
}
