//! Generated, credential-free configuration evidence for the public website.
//!
//! The website never recreates client configuration text. This module uses the
//! same pure adapters as the desktop application, then emits a committed static
//! TypeScript artifact for Vercel to serve.

use crate::adapter;
use crate::contracts::{
    AppKind, ConfigValue, ProviderProfile, RouteMode, SettingValue, SettingsValues, SwitchPlan,
    UpstreamProtocol,
};
use crate::ownership::{
    default_client_settings, default_provider_parameters, official_setting_directory, setting_spec,
    ChoiceControl, OfficialSettingDisposition, SettingControl, SettingOwner,
};
use crate::redact::REDACTED;
use serde::Serialize;

const DEMO_API_KEY: &str = "website-generated-demo-key";
// This has the only Codex capability shape accepted by the desktop adapter.
// It is deliberately a fixed demonstration value and is redacted before the
// generated website artifact is written.
const DEMO_CODEX_CAPABILITY: &str =
    "asb_codex_0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
const DEMO_GATEWAY: &str = "http://127.0.0.1:47821/codex/asb_codex_0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef/v1";
const BEDROCK_ENDPOINT: &str = "https://bedrock-runtime.us-east-1.amazonaws.com/v1";

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct WebsiteAssembly {
    codex: WebsiteAssemblyClient,
    claude: WebsiteAssemblyClient,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct WebsiteAssemblyClient {
    id: &'static str,
    tone: &'static str,
    client: &'static str,
    provider: String,
    parameter_fields: Vec<WebsiteAssemblyField>,
    provider_fields: Vec<WebsiteAssemblyField>,
    file_name: &'static str,
    file_path: &'static str,
    code_lines: Vec<String>,
    preserved_paths: Vec<String>,
    /// Paths owned by dedicated modules (global prompts, provider profiles,
    /// and the extensions workspace). Provider switching preserves them; the
    /// desktop manages each through its own contract and transaction.
    separate_modules: Vec<String>,
}

#[derive(Serialize)]
struct WebsiteAssemblyField {
    key: String,
    value: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    control: Option<&'static str>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    options: Vec<String>,
}

/// Renders the sole website configuration-evidence artifact.
pub fn typescript() -> String {
    let assembly = WebsiteAssembly {
        codex: client(AppKind::Codex),
        claude: client(AppKind::Claude),
    };
    let json = serde_json::to_string_pretty(&assembly).expect("website assembly serializes");

    format!(
        "// This file is generated by `cargo run -p asb-core --bin generate-website-assembly`.\n// Do not edit it by hand; the desktop adapters own these rendered lines.\n\nexport const configurationAssembly = {json} as const;\n\nexport type ConfigurationAssemblyClientId = keyof typeof configurationAssembly;\nexport type ConfigurationAssemblyClient = (typeof configurationAssembly)[ConfigurationAssemblyClientId];\nexport type ConfigurationAssemblyParameterField = {{\n  [ClientId in ConfigurationAssemblyClientId]: (typeof configurationAssembly)[ClientId][\"parameterFields\"][number];\n}}[ConfigurationAssemblyClientId];\nexport type ConfigurationAssemblyProviderField = {{\n  [ClientId in ConfigurationAssemblyClientId]: (typeof configurationAssembly)[ClientId][\"providerFields\"][number];\n}}[ConfigurationAssemblyClientId];\nexport type ConfigurationAssemblyFieldKey =\n  | ConfigurationAssemblyParameterField[\"key\"]\n  | ConfigurationAssemblyProviderField[\"key\"];\nexport type ConfigurationAssemblyControlValue =\n  ConfigurationAssemblyParameterField[\"options\"][number];\n"
    )
}

fn client(app: AppKind) -> WebsiteAssemblyClient {
    let plan = plan(app);
    let current = match app {
        AppKind::Codex => "",
        AppKind::Claude => "{}",
    };
    let candidate = adapter::render(current, &plan).expect("website demonstration plan is valid");
    let public_candidate = candidate
        .replace(DEMO_API_KEY, REDACTED)
        .replace(DEMO_CODEX_CAPABILITY, REDACTED);
    adapter::validate_syntax(app, &public_candidate)
        .expect("redacted website demonstration remains valid client configuration");
    let fields = adapter::owned_diff(app, &public_candidate, current)
        .expect("website demonstration candidate has an owned diff")
        .into_iter()
        .filter_map(|change| {
            change.after.map(|value| {
                let (control, options) = parameter_control(app, &change.key);
                WebsiteAssemblyField {
                    key: change.key,
                    value,
                    control,
                    options,
                }
            })
        });
    let (parameter_fields, provider_fields): (Vec<_>, Vec<_>) =
        fields.partition(|field| field.control.is_some());

    let (id, tone, client, file_name) = match app {
        AppKind::Codex => ("codex", "codex", "Codex", "config.toml"),
        AppKind::Claude => ("claude", "claude", "Claude Code", "settings.json"),
    };

    let directory = official_setting_directory(app);
    let separate_modules: Vec<String> = directory
        .iter()
        .filter(|entry| entry.disposition == OfficialSettingDisposition::SeparateModule)
        .map(|entry| entry.path.to_owned())
        .collect();
    let preserved_paths: Vec<String> = directory
        .into_iter()
        .filter(|entry| entry.disposition == OfficialSettingDisposition::PreserveOnly)
        .take(2)
        .map(|entry| entry.path.to_owned())
        .collect();

    WebsiteAssemblyClient {
        id,
        tone,
        client,
        provider: plan.profile.name,
        parameter_fields,
        provider_fields,
        file_name,
        file_path: app.config_label(),
        code_lines: public_candidate.lines().map(str::to_owned).collect(),
        preserved_paths,
        separate_modules,
    }
}

/// The website consumes the desktop ownership catalog's control metadata; it
/// never infers a visual control from a rendered configuration value.
fn parameter_control(app: AppKind, key: &str) -> (Option<&'static str>, Vec<String>) {
    let Some(spec) = setting_spec(app, key) else {
        return (None, vec![]);
    };
    if spec.owner != SettingOwner::Provider {
        return (None, vec![]);
    }

    match spec.control {
        SettingControl::Toggle => (
            Some("toggle"),
            ["automatic", "true", "false"]
                .into_iter()
                .map(str::to_owned)
                .collect(),
        ),
        SettingControl::Choice { presentation } => (
            Some(match presentation {
                ChoiceControl::Slider => "slider",
                ChoiceControl::Segment => "segment",
            }),
            std::iter::once("automatic".to_owned())
                .chain(
                    spec.allowed_values
                        .iter()
                        .map(|option| option.value.to_owned()),
                )
                .collect(),
        ),
        SettingControl::ModelPicker => (Some("model"), vec!["automatic".to_owned()]),
        SettingControl::None => (None, vec![]),
    }
}

fn plan(app: AppKind) -> SwitchPlan {
    let mut parameters = default_provider_parameters(app);
    match app {
        AppKind::Codex => {
            explicit(
                &mut parameters,
                "model_reasoning_effort",
                ConfigValue::Str("high".into()),
            );
            explicit(
                &mut parameters,
                "hide_agent_reasoning",
                ConfigValue::Bool(true),
            );
        }
        AppKind::Claude => {
            explicit(
                &mut parameters,
                "effortLevel",
                ConfigValue::Str("high".into()),
            );
            explicit(
                &mut parameters,
                "autoCompactEnabled",
                ConfigValue::Bool(true),
            );
        }
    }

    let (model, id) = match app {
        AppKind::Codex => ("GPT-6 Astra", "website-codex"),
        AppKind::Claude => ("Claude Opus 5.1", "website-claude"),
    };
    let plan = SwitchPlan::direct(
        ProviderProfile {
            id: id.into(),
            app,
            route_mode: RouteMode::Custom,
            name: "Amazon Bedrock".into(),
            model: Some(model.into()),
            base_url: Some(BEDROCK_ENDPOINT.into()),
            api_key: DEMO_API_KEY.into(),
            upstream_protocol: Some(UpstreamProtocol::Responses),
            responses_options: Some(crate::contracts::ResponsesOptions {
                request_mode: crate::contracts::ResponsesRequestMode::Standard,
            }),
            max_output_tokens: None.into(),
            model_options: None,
            parameters,
            notes: None,
            website_url: None,
            usage_query: None,
            official_quota_refresh_interval_minutes: None,
        },
        default_client_settings(app),
    );
    SwitchPlan::through_gateway(
        plan.profile,
        plan.client_settings,
        if app == AppKind::Codex {
            DEMO_GATEWAY.into()
        } else {
            "http://127.0.0.1:47821".into()
        },
        DEMO_API_KEY.into(),
    )
}

fn explicit(parameters: &mut SettingsValues, key: &str, value: ConfigValue) {
    parameters
        .settings
        .insert(key.into(), SettingValue::Explicit { value });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_website_assembly_matches_the_committed_artifact() {
        let generated = typescript();
        let committed = include_str!("../../../website/src/generated/configuration-assembly.ts");
        assert_eq!(committed, generated, "run the website assembly generator");
    }

    #[test]
    fn website_assembly_is_rendered_by_the_adapters_and_redacts_credentials() {
        let generated = typescript();

        assert!(generated.contains("model_provider"));
        assert!(generated.contains("ANTHROPIC_AUTH_TOKEN"));
        assert!(generated.contains(REDACTED));
        assert!(generated.contains("\"control\": \"toggle\""));
        assert!(generated.contains("\"control\": \"slider\""));
        assert!(generated.contains("\"preservedPaths\""));
        // MCP and skills are managed by the extensions workspace now: they
        // are dedicated modules the provider switch preserves, not
        // provider-owned or merely preserved fields.
        assert!(generated.contains("\"separateModules\""));
        assert!(generated.contains("mcp_servers.<id>"));
        assert!(generated.contains("skills.config"));
        assert!(generated.contains("~/.claude/skills/<name>/"));
        assert!(generated.contains("\"permissions\""));
        assert!(!generated.contains(DEMO_API_KEY));
    }
}
