use crate::ownership::spec::{OfficialSettingDisposition, OfficialSettingEntry};

/// Official user-level configuration families that require a dedicated
/// contract, or are intentionally preserved because their scope is not the
/// user's global preferences. The parameter form receives only `Direct`
/// entries derived from `setting_specs`; this table prevents the rest of the
/// official surface from silently becoming an accidental "unknown key".
pub(super) const CODEX_DIRECTORY_FAMILIES: &[OfficialSettingEntry] = &[
    OfficialSettingEntry {
        title: "ownership.directory.agentsMd.title",
        path: "$CODEX_HOME/AGENTS.md",
        related_paths: &[],
        disposition: OfficialSettingDisposition::SeparateModule,
        detail: "ownership.directory.agentsMd.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.modelProviders.title",
        path: "model_providers.<id>",
        related_paths: &[],
        disposition: OfficialSettingDisposition::SeparateModule,
        detail: "ownership.directory.modelProviders.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.agents.title",
        path: "agents",
        related_paths: &[
            "agents.enabled",
            "agents.max_concurrent_threads_per_session",
            "agents.interrupt_message",
            "agents.default_subagent_model",
        ],
        disposition: OfficialSettingDisposition::SeparateModule,
        detail: "ownership.directory.agents.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.agentsRole.title",
        path: "agents.<role>",
        related_paths: &["agents.<role>.config_file", "agents.<role>.description"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.agentsRole.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.mcpServers.title",
        path: "mcp_servers.<id>",
        related_paths: &[],
        disposition: OfficialSettingDisposition::SeparateModule,
        detail: "ownership.directory.mcpServers.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.skillsConfig.title",
        path: "skills.config",
        related_paths: &[],
        disposition: OfficialSettingDisposition::SeparateModule,
        detail: "ownership.directory.skillsConfig.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.hooks.title",
        path: "hooks",
        related_paths: &["plugins.<id>", "apps.<id>"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.hooks.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.permissions.title",
        path: "permissions.<name>",
        related_paths: &["sandbox_workspace_write", "default_permissions"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.permissions.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.shellEnvironmentPolicy.title",
        path: "shell_environment_policy",
        related_paths: &["features.network_proxy"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.shellEnvironmentPolicy.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.tuiKeymap.title",
        path: "tui.keymap",
        related_paths: &["tui.status_line", "tui.terminal_title"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.tuiKeymap.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.modelAutoCompactTokenLimit.title",
        path: "model_auto_compact_token_limit",
        related_paths: &[
            "model_auto_compact_token_limit_scope",
            "history.max_bytes",
            "tool_output_token_limit",
            "background_terminal_max_timeout",
            "memories.*_limit",
        ],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.modelAutoCompactTokenLimit.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.tuiNotificationMethod.title",
        path: "tui.notification_method",
        related_paths: &["tui.notification_conditions", "tui.status_line"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.tuiNotificationMethod.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.codexConfigToml.title",
        path: ".codex/config.toml",
        related_paths: &["projects.<path>.trust_level"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.codexConfigToml.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.requirementsToml.title",
        path: "requirements.toml",
        related_paths: &["auth.json", "ownership.path.sessionState"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.requirementsToml.detail",
    },
];

pub(super) const CLAUDE_DIRECTORY_FAMILIES: &[OfficialSettingEntry] = &[
    OfficialSettingEntry {
        title: "ownership.directory.claudeMd.title",
        path: "~/.claude/CLAUDE.md",
        related_paths: &[],
        disposition: OfficialSettingDisposition::SeparateModule,
        detail: "ownership.directory.claudeMd.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.claudePermissions.title",
        path: "permissions",
        related_paths: &[],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.claudePermissions.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.claudeHooks.title",
        path: "hooks",
        related_paths: &[],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.claudeHooks.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.env.title",
        path: "env",
        related_paths: &[],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.env.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.modelOverrides.title",
        path: "modelOverrides",
        related_paths: &["modelSettings", "modelPicker", "fallbackModel"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.modelOverrides.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.modelSettingsEffortLevel.title",
        path: "modelSettings.<model>.effortLevel",
        related_paths: &["modelSettings.<model>.fastMode"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.modelSettingsEffortLevel.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.outputStyles.title",
        path: "outputStyles.<name>",
        related_paths: &["outputStyle"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.outputStyles.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.claudeJson.title",
        path: "~/.claude.json",
        related_paths: &[
            ".mcp.json",
            "projects.<path>.mcpServers",
            "projects.<path>.disabledMcpServers",
        ],
        disposition: OfficialSettingDisposition::SeparateModule,
        detail: "ownership.directory.claudeJson.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.claudeSkills.title",
        path: "~/.claude/skills/<name>/",
        related_paths: &["skillOverrides.<name>", ".claude/skills/<name>/"],
        disposition: OfficialSettingDisposition::SeparateModule,
        detail: "ownership.directory.claudeSkills.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.enabledPlugins.title",
        path: "enabledPlugins",
        related_paths: &["extraKnownMarketplaces"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.enabledPlugins.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.voice.title",
        path: "voice",
        related_paths: &["apiKeyHelper", "otelHeadersHelper"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.voice.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.claudeSettingsJson.title",
        path: ".claude/settings.json",
        related_paths: &[".claude/settings.local.json", "managed-settings.json"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.claudeSettingsJson.detail",
    },
    OfficialSettingEntry {
        title: "ownership.directory.claudeCredentialsJson.title",
        path: "~/.claude/.credentials.json",
        related_paths: &["~/.claude.json"],
        disposition: OfficialSettingDisposition::PreserveOnly,
        detail: "ownership.directory.claudeCredentialsJson.detail",
    },
];
