use crate::ownership::spec::{SettingOwner, ToggleSpec};

/// The official general-config toggles offered on the settings page. Keys
/// must stay inside the owned-key tables above.
pub const CODEX_TOGGLES: &[ToggleSpec] = &[
    ToggleSpec {
        key: "hide_agent_reasoning",
        owner: SettingOwner::Provider,
        label: "ownership.label.hide_agent_reasoning",
        group: "ownership.group.modelBehavior",
    },
    ToggleSpec {
        key: "show_raw_agent_reasoning",
        owner: SettingOwner::Provider,
        label: "ownership.label.show_raw_agent_reasoning",
        group: "ownership.group.modelBehavior",
    },
    ToggleSpec {
        key: "tui.animations",
        owner: SettingOwner::Client,
        label: "ownership.label.tuiAnimations",
        group: "ownership.group.terminalUi",
    },
    ToggleSpec {
        key: "tui.show_tooltips",
        owner: SettingOwner::Client,
        label: "ownership.label.tuiShow_tooltips",
        group: "ownership.group.terminalUi",
    },
    ToggleSpec {
        key: "tui.notifications",
        owner: SettingOwner::Client,
        label: "ownership.label.tuiNotifications",
        group: "ownership.group.terminalUi",
    },
    ToggleSpec {
        key: "tui.raw_output_mode",
        owner: SettingOwner::Client,
        label: "ownership.label.tuiRaw_output_mode",
        group: "ownership.group.terminalUi",
    },
    ToggleSpec {
        key: "tui.vim_mode_default",
        owner: SettingOwner::Client,
        label: "ownership.label.tuiVim_mode_default",
        group: "ownership.group.terminalUi",
    },
    ToggleSpec {
        key: "disable_paste_burst",
        owner: SettingOwner::Client,
        label: "ownership.label.disable_paste_burst",
        group: "ownership.group.terminalUi",
    },
    ToggleSpec {
        key: "tools.view_image",
        owner: SettingOwner::Client,
        label: "ownership.label.toolsView_image",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.memories",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresMemories",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.prevent_idle_sleep",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresPrevent_idle_sleep",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "check_for_update_on_startup",
        owner: SettingOwner::Client,
        label: "ownership.label.check_for_update_on_startup",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "allow_login_shell",
        owner: SettingOwner::Client,
        label: "ownership.label.allow_login_shell",
        group: "ownership.group.safetyAndApprovals",
    },
    ToggleSpec {
        key: "sandbox_workspace_write.network_access",
        owner: SettingOwner::Client,
        label: "ownership.label.sandbox_workspace_writeNetwork_access",
        group: "ownership.group.safetyAndApprovals",
    },
    ToggleSpec {
        key: "sandbox_workspace_write.exclude_tmpdir_env_var",
        owner: SettingOwner::Client,
        label: "ownership.label.sandbox_workspace_writeExclude_tmpdir_env_var",
        group: "ownership.group.safetyAndApprovals",
    },
    ToggleSpec {
        key: "sandbox_workspace_write.exclude_slash_tmp",
        owner: SettingOwner::Client,
        label: "ownership.label.sandbox_workspace_writeExclude_slash_tmp",
        group: "ownership.group.safetyAndApprovals",
    },
    ToggleSpec {
        key: "windows.sandbox_private_desktop",
        owner: SettingOwner::Client,
        label: "ownership.label.windowsSandbox_private_desktop",
        group: "ownership.group.safetyAndApprovals",
    },
    ToggleSpec {
        key: "feedback.enabled",
        owner: SettingOwner::Client,
        label: "ownership.label.feedbackEnabled",
        group: "ownership.group.privacyAndData",
    },
    ToggleSpec {
        key: "analytics.enabled",
        owner: SettingOwner::Client,
        label: "ownership.label.analyticsEnabled",
        group: "ownership.group.privacyAndData",
    },
    ToggleSpec {
        key: "tui.alternate_screen",
        owner: SettingOwner::Client,
        label: "ownership.label.tuiAlternate_screen",
        group: "ownership.group.terminalUi",
    },
    ToggleSpec {
        key: "tui.resume_cwd",
        owner: SettingOwner::Client,
        label: "ownership.label.tuiResume_cwd",
        group: "ownership.group.terminalUi",
    },
    ToggleSpec {
        key: "features.apps",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresApps",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.hooks",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresHooks",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.shell_tool",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresShell_tool",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.enable_request_compression",
        owner: SettingOwner::Provider,
        label: "ownership.label.featuresEnable_request_compression",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.skill_mcp_dependency_install",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresSkill_mcp_dependency_install",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.fast_mode",
        owner: SettingOwner::Provider,
        label: "ownership.label.featuresFast_mode",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.shell_snapshot",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresShell_snapshot",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.unified_exec",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresUnified_exec",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.multi_agent",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresMulti_agent",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.goals",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresGoals",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.remote_plugin",
        owner: SettingOwner::Client,
        label: "ownership.label.featuresRemote_plugin",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "features.personality",
        owner: SettingOwner::Provider,
        label: "ownership.label.featuresPersonality",
        group: "ownership.group.toolsAndFeatures",
    },
    ToggleSpec {
        key: "memories.generate_memories",
        owner: SettingOwner::Client,
        label: "ownership.label.memoriesGenerate_memories",
        group: "ownership.group.privacyAndData",
    },
    ToggleSpec {
        key: "memories.use_memories",
        owner: SettingOwner::Client,
        label: "ownership.label.memoriesUse_memories",
        group: "ownership.group.privacyAndData",
    },
    ToggleSpec {
        key: "memories.disable_on_external_context",
        owner: SettingOwner::Client,
        label: "ownership.label.memoriesDisable_on_external_context",
        group: "ownership.group.privacyAndData",
    },
];

pub const CLAUDE_TOGGLES: &[ToggleSpec] = &[
    ToggleSpec {
        key: "alwaysThinkingEnabled",
        owner: SettingOwner::Provider,
        label: "ownership.label.alwaysThinkingEnabled",
        group: "ownership.group.modelBehavior",
    },
    ToggleSpec {
        key: "autoCompactEnabled",
        owner: SettingOwner::Provider,
        label: "ownership.label.autoCompactEnabled",
        group: "ownership.group.modelBehavior",
    },
    ToggleSpec {
        key: "showThinkingSummaries",
        owner: SettingOwner::Provider,
        label: "ownership.label.showThinkingSummaries",
        group: "ownership.group.modelBehavior",
    },
    ToggleSpec {
        key: "spinnerTipsEnabled",
        owner: SettingOwner::Client,
        label: "ownership.label.spinnerTipsEnabled",
        group: "ownership.group.interfaceAndInteraction",
    },
    ToggleSpec {
        key: "autoScrollEnabled",
        owner: SettingOwner::Client,
        label: "ownership.label.autoScrollEnabled",
        group: "ownership.group.interfaceAndInteraction",
    },
    ToggleSpec {
        key: "emojiCompletionEnabled",
        owner: SettingOwner::Client,
        label: "ownership.label.emojiCompletionEnabled",
        group: "ownership.group.interfaceAndInteraction",
    },
    ToggleSpec {
        key: "promptSuggestionEnabled",
        owner: SettingOwner::Client,
        label: "ownership.label.promptSuggestionEnabled",
        group: "ownership.group.interfaceAndInteraction",
    },
    ToggleSpec {
        key: "showTurnDuration",
        owner: SettingOwner::Client,
        label: "ownership.label.showTurnDuration",
        group: "ownership.group.interfaceAndInteraction",
    },
    ToggleSpec {
        key: "syntaxHighlightingDisabled",
        owner: SettingOwner::Client,
        label: "ownership.label.syntaxHighlightingDisabled",
        group: "ownership.group.interfaceAndInteraction",
    },
    ToggleSpec {
        key: "terminalProgressBarEnabled",
        owner: SettingOwner::Client,
        label: "ownership.label.terminalProgressBarEnabled",
        group: "ownership.group.interfaceAndInteraction",
    },
    ToggleSpec {
        key: "fileCheckpointingEnabled",
        owner: SettingOwner::Client,
        label: "ownership.label.fileCheckpointingEnabled",
        group: "ownership.group.filesAndGit",
    },
    ToggleSpec {
        key: "respectGitignore",
        owner: SettingOwner::Client,
        label: "ownership.label.respectGitignore",
        group: "ownership.group.filesAndGit",
    },
    ToggleSpec {
        key: "includeGitInstructions",
        owner: SettingOwner::Client,
        label: "ownership.label.includeGitInstructions",
        group: "ownership.group.filesAndGit",
    },
    ToggleSpec {
        key: "autoMemoryEnabled",
        owner: SettingOwner::Client,
        label: "ownership.label.autoMemoryEnabled",
        group: "ownership.group.filesAndGit",
    },
    ToggleSpec {
        key: "ultracode",
        owner: SettingOwner::Provider,
        label: "ownership.label.ultracode",
        group: "ownership.group.modelBehavior",
    },
];
