export const WEB_DEVELOPMENT_BACKEND_ORIGIN = "http://127.0.0.1:1422";
export const WEB_DEVELOPMENT_BACKEND_HEALTH_URL = `${WEB_DEVELOPMENT_BACKEND_ORIGIN}/health`;
export const WEB_DEVELOPMENT_BACKEND_READY_INTERVAL_MS = 100;
